"""clean_duplicate_token_constraint

Revision ID: a7b2ebfdbd67
Revises: d71bd74812b4
Create Date: 2026-10-08 21:14:57.378016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b2ebfdbd67'
down_revision: Union[str, Sequence[str], None] = 'd71bd74812b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('organization_invitations_token_key'), 'organization_invitations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('organization_invitations_token_key'), 'organization_invitations', ['token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
